CREATE FUNCTION GET_NUM_OF_TESTS_PER_DAY(DATE DATE)
RETURNS INT
RETURN
    SELECT COUNT(DATE)
    FROM TEST
    WHERE TEST.DATE = DATE;


--test calling the function
VALUES FN45421.GET_NUM_OF_TESTS_PER_DAY('12.05.2020');

CREATE FUNCTION GET_MED_PATIENT(M_PAT_ID CHAR(8))
RETURNS TABLE(MEDS VARCHAR(64))
RETURN
    SELECT NAME
    FROM MEDICATION
    WHERE PAT_ID = M_PAT_ID;

--test calling the function
SELECT *
FROM TABLE(FN45421.GET_MED_PATIENT('A1234568')) T;

CREATE FUNCTION GET_ALL_REG_PATIENTS(M_DATE DATE)
RETURNS TABLE(ID CHAR(8),REG_PATIENTS VARCHAR(255))
RETURN
    SELECT pat_id, pat_name
    FROM PATIENT
    WHERE M_DATE = ADMISSION_DATE;

--test calling the function
SELECT *
FROM TABLE(FN45421.GET_ALL_REG_PATIENTS('12.05.2020')) T;

CREATE FUNCTION COUNT_ALL_APP_PHYS(M_PHYS_ID CHAR(4),M_DATE DATE)
RETURNS TABLE(NAME_PHYS VARCHAR(128),NUM_APP INT)
RETURN
    SELECT PHYS_NAME, COUNT(APP_ID)
    FROM APPOINTMENT,PHYSICIAN
    WHERE APPOINTMENT.PHYS_ID = PHYSICIAN.PHYS_ID
          AND  M_DATE = APP_DATE
          AND APPOINTMENT.PHYS_ID = M_PHYS_ID
    GROUP BY PHYS_NAME;

--test calling the function
SELECT *
FROM TABLE(FN45421.COUNT_ALL_APP_PHYS(1000, '12.05.2020')) T;

CREATE FUNCTION GET_NUM_OF_PHYS_IN_DEP(M_DEPT_NAME VARCHAR(50))
RETURNS INT
RETURN SELECT COUNT(PHYS_NAME)
       FROM PHYSICIAN
       WHERE DEP_NAME = M_DEPT_NAME;


--test calling the function
VALUES FN45421.GET_NUM_OF_PHYS_IN_DEP('Onkologiq');

CREATE FUNCTION GET_SHIFT_INFO(ID_NURSE CHAR(4))
RETURNS CHAR(1)
RETURN SELECT SHIFT
       FROM NURSE
       WHERE NURSE_ID = ID_NURSE;

--test calling the function
VALUES FN45421.GET_SHIFT_INFO('4234');

CREATE FUNCTION GET_ROOM_NUM(PATID CHAR(8))
RETURNS INT
RETURN SELECT ROOM_NUM
       FROM NURSING_SERVICE
       WHERE PAT_ID = PATID;

--test calling the function
VALUES FN45421.GET_ROOM_NUM('A1234568');

CREATE FUNCTION GET_INFO_MED(M_MED_ID CHAR(12))
RETURNS TABLE( M_NAME VARCHAR(64), M_DESCRIPTION VARCHAR(512), M_PRICE DECIMAL)
RETURN SELECT NAME, DESCRIPTION, PRICE
       FROM MEDICATION
       WHERE MED_ID = M_MED_ID;

--test calling the function
SELECT *
FROM TABLE(FN45421.GET_INFO_MED('POOPPW123790')) T;


